### ISSUE TITLE
src/CMakeLists.txt references deleted file algorithms/SORT-OMPTarget.cpp

### ISSUE THREAD

**Issue by abbotts** [LLNL/RAJAPerf#103]
PR #101 added this line referencing a file that was deleted during the PR review. This breaks OMPTarget configure.

https://github.com/LLNL/RAJAPerf/blob/develop/src/CMakeLists.txt#L187

It looks like PR #102 will probably fix this as a side effect, so there probably isn't any action needed besides what's already there.

**Comment by rhornung67** [comment]
@abbotts PR #102 is now merged into develop. Please let us know if if you run into any other issues. Thank you.

**Comment by abbotts** [comment]
Thanks @rhornung67 ! I can configure cleanly now. I get a couple build errors with the OMP Target backend, but those could be issues with our compiler. I'll investigate and open new issues if needed.

**Comment by rhornung67** [comment]
@abbotts thanks for confirming this resolved your earlier issue. Yes, please let us know if you hit more snags.
