### ISSUE TITLE
Larger polybench kernel sizes broken with cuda and hip

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJAPerf#113]
The larger sizes for the polybench kernels cause errors in the cuda and hip variants. The sizes exceed the max block/workgroup size and cause the kernel launches to fail.

**Comment by rhornung67** [comment]
I agree this would be good to fix. It will take more or less work to address depending how much guidance we want to give to users on this.

**Comment by artv3** [comment]
One fix could be to use the thread_loop policies and the native analogues. This would also construct examples which expose issues in compiler optimizations for the block stride thread loops we have seen.

**Comment by MrBurmark** [comment]
This could be an opportunity to try both loop and tile+direct for different problem sizes and see what performance difference there is.

**Comment by CRobeck** [comment]
What is the disadvantage here to just limiting the threads per threadblock to be within the runtime max?

**Comment by rhornung67** [comment]
@MrBurmark do you want to take a stab at fleshing out the runtime selection of loop or tile+direct policies for a kernel or two? When we settle on something that we like, I can work this in to the rest of the kernels.

**Comment by rhornung67** [comment]
> What is the disadvantage here to just limiting the threads per threadblock to be within the runtime max?

@MrBurmark has experimented with threads/block more than I have. @MrBurmark any thoughts on this?

**Comment by MrBurmark** [comment]
The tile+direct policies can expose more parallelism and map to the hardware more consistently, but that consistency can also create small blocks depending on the parameters. The loop policies don't tend to optimize as well and have a little extra overhead compared to the direct policies even when they are well optimized. @artv3 mentioned this and it might be a good idea to have both versions for comparison and expose when compilers are optimizing poorly.

**Comment by rhornung67** [comment]
Fixed and merged into develop
