### ISSUE TITLE
Output features used by each kernel

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJAPerf#116]
Outputting the features used by each kernel can help analyze the differences in results between different architectures. This should help identify performance features that differ between different architectures; making it easier to note where performance is in line or out of line with expected architecture performance differences.

**Comment by rhornung67** [comment]
👍 I'll assign this to myself.

**Comment by DavidPoliakoff** [comment]
Yeah, there's a neat summer student project where you use these features, a spec sheet for the architecture, and some reference architecture's timings to estimate the time it should take on a new arch. This would be independently useful though, we often rely on a hand-wavy version of the same thing to discuss the Perfsuite with vendors

**Comment by rhornung67** [comment]
I'll also add a run-time mechanism to choose which kernels to run based on feature to exercise.

**Comment by rhornung67** [comment]
@MrBurmark we still want to do this, correct? I'm starting to work on it.

**Comment by MrBurmark** [comment]
Ya, I still think its a good idea.

**Comment by rhornung67** [comment]
OK. I'm on it.

**Comment by rhornung67** [comment]
@MrBurmark I have a branch with basic support for outputting features used by the kernels. I need to add a mechanism to select which kernels to run based on features.  What I have now reports that a kernel uses RAJA::kernel or it doesn't, for example. Should we distinguish kernels that use multiple lambdas from the single lambda case?

**Comment by MrBurmark** [comment]
@rhornung67 I'm not sure if that level of detail is useful to distinguish or not, do you expect compilers may have a harder time with multi-lambda kernels than single lambda kernels?

**Comment by rhornung67** [comment]
Not really. I wanted to know what you thought. I'll go with what I have now. We can modify in the future if we think that is useful at some point.
