### ISSUE TITLE
Make threads per block parameter a run time choice

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#132]
Currently, the threads per block parameter is hard-coded in each GPU kernel variant source file.

- [ ] For each GPU back-end (and kernel?), pick a default block size, but allow it to be changed with a runtime option.
- [ ] Report this information in the output summary file.

**Comment by artv3** [comment]
We can do this with RAJA Teams, but Forall/Kernel functions template on the threads per block size.

**Comment by rhornung67** [comment]
Right, but I think we should be able to set it as a runtime option. Or am I confused?

**Comment by rhornung67** [comment]
can reopen issue if we decide to do this...
