### ISSUE TITLE
Add option specify size of kernels to run directly

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#134]
For example, we want to be able to do something like: run all forall kernels with loop length 1,000,000.

**Comment by rhornung67** [comment]
@MrBurmark do we want this to be something like "run each kernel with size = N" and we choose how to do that for each kernel. Forall kernels are pretty straightforward for this. Others with multiple loops, or nested loops (and loop nest patterns) will take some thought.

**Comment by MrBurmark** [comment]
@rhornung67 Sure, we can at least get a start on it. Currently the "problem size" is expressed as iterations per rep. How about we split that into iterations per rep and a more abstract problem size that can mean different things for each kernel. How about adding other bits of information like bytes read per rep and kernels per rep to the per kernel information to handle things like bandwidth, kernel launch overhead, and other things.

**Comment by rhornung67** [comment]
@MrBurmark All good ideas. Let's use this issue to sketch out a set of tasks for this, with as much detail about how we define problem size, bytes read/written per rep, etc. Then, we can tackle the tasks as we have time.

**Comment by MrBurmark** [comment]
@rhornung67 I talked with @ajkunen about ltimes so I think I have a good enough handle on problem size for everything but polybench to move forward and make a PR where we can discuss problem size. Regarding the other metrics, I plan to take my existing PRs #126 and #128 and convert them to output their info as per kernel information so we can discuss the exact meaning of things like bytes read and written in those PRs. Regarding the per kernel info that we already have, iterations per rep is mostly done correctly, but some kernels with multiple loops like ENERGY only report the number of iterations in a single loop. Should we count all the iterations in all the loops in multi loop kernels?

**Comment by rhornung67** [comment]
Not sure about your last question, but the rest sounds good. I look through the polybench kernels after your PRs are ready. For outputting other kernel metrics, we should do this in separate report file(s). We should discuss how best to organize the output so it's clear.

**Comment by MrBurmark** [comment]
I think we're adding enough per kernel information that we may just want to have a file for general information about the kernels instead of only printing that to the screen.

**Comment by rhornung67** [comment]
Agreed. It would make the output in the other files simpler. Please create an issue describing the information we want to include in the summary file and how we think it should be presented. Thanks.

**Comment by MrBurmark** [comment]
@rhornung67 See #143 for how I'm adding a function to get the problem size for each kernel.

**Comment by MrBurmark** [comment]
See #144 for my kernel information file output ideas.

**Comment by MrBurmark** [comment]
I'm adding a --size option to directly specify a problem size to run. I'm planning to make it an error to set size and sizefact in the same run, what do you think?

**Comment by rhornung67** [comment]
Sounds good. I agree on the error.

**Comment by rhornung67** [comment]
I commented on your PR about run sizes.

**Comment by MrBurmark** [comment]
Option added in #143.
