### ISSUE TITLE
Add bandwidth output

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#135]
- [ ] Determine how to instrument the kernels to generate bandwidth output. One possibility: # bytes read + # bytes written in each loop iteration * total number of loop iterations (i.e., run size * # kernel reps).  Other possibilities?
- [ ] Determine how best to report this in an output file

**Comment by MrBurmark** [comment]
Another way to count memory use outside of the per iterate level is to count the memory use across the whole loop. For example a sequential reduction reads and writes the reduction variable once per loop iteration but uses the same memory for the whole loop so the first scheme would 1 read and 1 write per iterate and the second would only count 1 read and 1 write for the whole loop. The main reason I mention the second method is to avoid any ambiguity over how to treat things like coefficients which are also used once per iterate but are generally not counted when considering bandwidth.

**Comment by rhornung67** [comment]
@MrBurmark this issue can be closed, correct? You've added the read/write counts to all kernels and this is reported in the kernel info output file.

**Comment by MrBurmark** [comment]
Yes it can be calculated from that output now.
