### ISSUE TITLE
Add per loop timing output

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#136]
Ideally, this may help us understand GPU kernel launch overhead/latency.

How best to do this? Count total number of kernels launched per kernel variant and divide total execution time by this number..

Note: some kernels actually launch multiple GPU kernels within them; e.g., many polybench kernels do this and apps kernels like PRESSURE and ENERGY

**Comment by MrBurmark** [comment]
Since this is mainly targeted at launch overhead/latency of loops I think it makes sense to count the places that parallelism is applied in the loop structure, like the places that omp for or kernel launch are done. What do people think about that for kernels with multiple loops?

**Comment by rhornung67** [comment]
I think that makes sense, but need to ruminate on it a bit more. (I like using "$10 words" in GitHub issue comments... :-) )

**Comment by rhornung67** [comment]
@MrBurmark I believe this one is done also, correct?

**Comment by MrBurmark** [comment]
Yes it can now be calculated from the kernel output.
