### ISSUE TITLE
Add kernel details output file

### ISSUE THREAD

**Issue by MrBurmark** [LLNL/RAJAPerf#144]
The names of kernels, the number of iterations per repetition and the number of repetitions are already output to the screen. Take that output and more and output it to a file so there is a record of the kernels run and their configuration. I'm imagining something like a CSV file with these columns of information:

- [ ] Kernel name (meaning: the group_kernel format of the kernel name)
- [ ] problem size (meaning: the largest *parallel* iteration space over all kernels launched in a kernel instance -- note: several kernels actually launch multiple kernels and some of these have multiple sizes)
- [ ] number of repetitions (meaning: the number of time a kernel is run during a single pass through the suite)
- [ ] iterations per repetition (meaning: sum of sizes of parallel iteration spaces over all kernels launched in a kernel instance -- see "problem size" above)
- [ ] loops/kernels per repetition (meaning: total number of kernels launched in each kernel instance)
- [ ] reads & writes per repetition (meaning: # bytes read and written for each repetition of kernel)
- [ ] FLOPs per repetition (meaning: # floating point operations for each repetition of kernel. Counting any floating point operation +, -, *, /, sqrt, exp, sin, cos, etc as one FLOP. Currently not counting ops like abs and comparisons, but should it?)
- [ ] features used (meaning: list of RAJA features used by each kernel)

**Comment by rhornung67** [comment]
what do you mean be "iterations per repetition" for kernels that launch multiple kernels, potentially of different sizes? also, is "loops/kernels per repetition" meant to be the total number of kernels launched per repetition?

**Comment by MrBurmark** [comment]
For "iterations per repetition" I meant what we already call "iterations/rep." This mostly picks something like the max iterations when there are multiple kernels of different sizes. Though we could also change it to be the total iterations per repetition including repetitions from different loops.
Yes the "loops/kernels per repetition" does mean the number of kernel launches per repetition.

**Comment by rhornung67** [comment]
OK. Thanks. I'll work on this after we get enough things merged to address all of these items.

**Comment by rhornung67** [comment]
@MrBurmark @artv3 do the definitions I added to the items above make sense? I'm trying to make them clear so that we all have the same understanding and are in agreement about what they mean.  Thanks.

**Comment by MrBurmark** [comment]
Did the edit take, I don't see any changes.

**Comment by rhornung67** [comment]
Sorry. Do you see it now?

**Comment by artv3** [comment]
For problem size, what about measuring by input array size? Or how do we measure in the case of hierarchical parallelism?

**Comment by rhornung67** [comment]
@artv3 yes, i think product of blocks and threads is correct. we're trying to define problem size as the amount of parallelism in the kernel. For example, consider a mat-vec: y = A x, where A is an R x C matrix. The size of this kernel would be R since you can do each row-vector dot product in parallel, but each dot product has to be done sequentially. For a vector dot product (x, y), where x and y are vectors of length N, the size would be N because we do the partial sums in parallel. Do you think this makes sense?

**Comment by artv3** [comment]
Yes.  In case of a block or grid stride loop would we still count it as R? or would it be less since some threads would execute more than one dot product.

**Comment by rhornung67** [comment]
That's a good point.  I'm not sure how to handle this? @MrBurmark thoughts?

**Comment by MrBurmark** [comment]
I think the problem size should be independent of the implementation details like grid stride or block stride. So I would say it should be the full size or R.

**Comment by rhornung67** [comment]
I tend to agree and it will make things much easier for us when we transform the kernels to use grid/block stride loops.

**Comment by MrBurmark** [comment]
@rhornung67 I added a basic description for FLOPs here.
There are some unanswered questions like what counts as a FLOP, when I added the counts I counted operations like +, -, *, /, sqrt, exp as one flop each, and ignored things like abs, and comparisons. Maybe we can add an asterisk for kernels that use more complex operations so they can be easily identified.
What do people think we should count here?

**Comment by willkill07** [comment]
I am in agreement regarding abs not being deemed a FP operation.

FP comparisons are a bit unique, but the throughput and latency on modern architectures are 1 cycle.

I think it would add value to say which kernels have special operations (such as abs and floating point comparisons), but they need not be reported.
