### ISSUE TITLE
verification is not sufficient

### ISSUE THREAD

**Issue by jeffhammond** [LLNL/RAJAPerf#170]
I haven't determined how many cases are affected but at least in the case of `FIRST_DIFF`, a null implementation passes the verification test.

Is there a way to enable tedious verification by comparing to the sequential implementation?

**Comment by rhornung67** [comment]
@jeffhammond can you provide more details? I don't understand what you see to be an issue. 

The way the kernels are set up is that the result arrays used in the checksum calculations are initialized to zeros. So when a kernel is not run, it's checksum is computed to be zero, while other variants that do run will have non-zero checksums. This implies something is not correct. 

I interpret what you call a "null implementation" is when there is no kernel implementation to run. Is that correct? For the FIRST_DIFF kernel, I commented out the Lambda_Seq kernel implementation. The checksums and differences I see are:

Kernel
........................................................
Variants         Checksum                    Checksum Diff (vs. first variant listed)
----------------------------------------------------------------------------------------
Lcals_FIRST_DIFF
........................................................
Base_Seq         0.030968442117378508494     0.0000000000000000000
Lambda_Seq       0.0000000000000000000       0.030968442117378508494
RAJA_Seq         0.030968442117378508494     0.0000000000000000000
Base_OpenMP      0.030968442117378508494     0.0000000000000000000
Lambda_OpenMP    0.030968442117378508494     0.0000000000000000000
RAJA_OpenMP      0.030968442117378508494     0.0000000000000000000

-------------------------------------------------------

This shows that there was no Lambda_Seq variant run, its checksum is zero, and it's difference with the reference variant (Base_Seq in this case) is equal to the checksum for the ref variant.

By default, the Base_Seq variant is the reference variant that all other variant checksums are compared to. You can change the reference variant via a command line option. Run 'raja-perf.exe -h' to see what the options are.

**Comment by jeffhammond** [comment]
Ah, I didn't realize that erroneous results wouldn't be flagged in the timing output.

The good news is that the `StdPar` ports are mostly validating.  The exceptions are all similar:

```
Kernel         
........................................................
Variants       Checksum                    Checksum Diff (vs. first variant listed)
----------------------------------------------------------------------------------------
Polybench_2MM  
........................................................
Base_Seq       94796362525.148559570       0.0000000000000000000       
Lambda_Seq     94796362525.148559570       0.0000000000000000000       
RAJA_Seq       94796362525.148559570       0.0000000000000000000       
Base_StdPar    73572873505.442749023       21223489019.705810547       
Lambda_StdPar  73572873505.442749023       21223489019.705810547       

-------------------------------------------------------
Polybench_3MM  
........................................................
Base_Seq       2389036157684.3740234       0.0000000000000000000       
Lambda_Seq     2389036157684.3740234       0.0000000000000000000       
RAJA_Seq       2389036157684.3740234       0.0000000000000000000       
Base_StdPar    1938454638092.9169922       450581519591.45703125       
Lambda_StdPar  1938446145134.1032715       450590012550.27075195       

-------------------------------------------------------
Polybench_GEMM 
........................................................
Base_Seq       2880816241.1435256004       0.0000000000000000000       
Lambda_Seq     2880816241.1435256004       0.0000000000000000000       
RAJA_Seq       2880816241.1435256004       0.0000000000000000000       
Base_StdPar    2617732870.7275967598       263083370.41592884064       
Lambda_StdPar  2617732870.7275967598       263083370.41592884064       

-------------------------------------------------------
```

**Comment by rhornung67** [comment]
@jeffhammond I broke the output into separate files for timing, checksums, etc. I can add something to the timing output to indicate when checksums are off if you think that would be helpful.  Also, I have a PR under review that scales checksums for certain kernels so that we can definitively state that a checksum difference of, say, < 1e-8 for any kernel or variant is considered a correct result. That will appear in the next release, which should be out by the end of next week.

**Comment by jeffhammond** [comment]
Cool. Yeah, I mostly want non-validating results to not show performance because obviously getting the wrong answer at any speed doesn't matter. 

But now that I'm not ignorant of the way it works, it isn't hard to deal with what's there already. 

I did find a fun issue with reductions in DOT that revealed itself via an error of 1e-10 earlier today, so I'd be careful tolerating too much error in that one.

**Comment by rhornung67** [comment]
Thanks for the tip.
