### ISSUE TITLE
add a reduction kernel to the warmup kernels

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#173]
this will prevent first reduction kernel run showing a significant slowdown

**Comment by rhornung67** [comment]
@rhornung67 if we run all desired variants of the DAXPY and DOT kernel, will that be sufficient to prevent all kernels from running slower the first time? Or, do we need to run all kernels as warmup?   I need to think about it, but we may be able to rig up something to run each kernel in a "warmup mode" (smallish size and rep count) first and ignore the timing for that.

**Comment by MrBurmark** [comment]
That would probably be enough. The only thing that would potentially miss is if the memory pools need to allocate more memory for larger problems or problems with more reducers.

**Comment by rhornung67** [comment]
OK. I'll do the kernel with 3 reductions instead and run it at full size.

**Comment by rhornung67** [comment]
Done and merged into develop.
