### ISSUE TITLE
SYCL kernels to be added

### ISSUE THREAD

**Issue by homerdin** [LLNL/RAJAPerf#195]
The following is a list of kernels which do not have their SYCL variants implemented in #122.

- [ ] Basic_MAT_MAT_SHARED: Missing SYCL teams implementation
- [ ] Basic_PI_ATOMIC: Missing SYCL atomics implementation
- [ ] Basic_PI_REDUCE: Ready to be implemented
- [ ] Lcals_FIRST_MIN: Ready to be implemented
- [ ] Lcals_FIRST_SUM: Ready to be implemented
- [ ] Polybench_3MM: Ready to be implemented
- [ ] Polybench_ADI: Ready to be implemented
- [ ] Polybench_ATAX: Ready to be implemented
- [ ] Polybench_FDTD_2D: Ready to be implemented
- [ ] Polybench_FLOYD_WARSHALL: Ready to be implemented
- [ ] Polybench_GEMM: Ready to be implemented
- [ ] Polybench_GEMVER: Ready to be implemented
- [ ] Polybench_HEAT_3D: Ready to be implemented
- [ ] Polybench_JACOBI_1D: Ready to be implemented
- [ ] Polybench_JACOBI_2D: Ready to be implemented
- [ ] Polybench_MVT: Ready to be implemented
- [ ] Apps_DIFFUSION3DPA: Missing SYCL teams implementation
- [ ] Apps_HALOEXCHANGE: Ready to be implemented
- [ ] Apps_HALOEXCHANGE_FUSED: Missing SYCL workpool implementation
- [ ] Apps_MASS3DPA: Missing SYCL teams implementation
- [ ] Algorithm_SORT: Missing SYCL sort implementation
- [ ] Algorithm_SORTPAIRS: Missing SYCL sort implementation

**Comment by artv3** [comment]
@homerdin getting a base version sounds good to me. I can assist with developing the RAJA Teams backend version.

**Comment by homerdin** [comment]
Opening new issue with updated SYCL kernel implementation.
