### ISSUE TITLE
Unrecognized warning pragmas: unrecognized GCC pragma

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJAPerf#220]
With the following build config: build_lc_blueos-nvcc10.2.89-sm_70-gcc8.3.1
We get the following warnings:

```
/RAJAPerf/tpl/RAJA/include/RAJA/pattern/tensor/internal/MatrixMatrixMultiply.hpp(102): warning: unrecognized GCC pragma

/RAJAPerf/tpl/RAJA/include/RAJA/pattern/tensor/internal/MatrixMatrixMultiply.hpp(107): warning: unrecognized GCC pragma
```

**Comment by artv3** [comment]
ping: @ajkunen, I'm taking a look at these but just wanted to check in and ask if you might have some insight? I suspect we might be missing some macro logic.

**Comment by artv3** [comment]
My RAJA was out of date, the latest version resolves this.

**Comment by rhornung67** [comment]
whew! I thought we had resolved those issues. @ajkunen no need to think about this. 😄
