### ISSUE TITLE
Install bin/raja-perf.exe

### ISSUE THREAD

**Issue by slabasan** [LLNL/RAJAPerf#284]
Noticed that only `include/` and `lib/` are getting installed, but not `bin/`. It would be helpful to have this executable installed as well.

**Comment by rhornung67** [comment]
@slabasan I'm working on a RAJA Perf release. The executable install fix will be addressed in that.
We typically don't use it that way. Sorry for the oversight.

**Comment by rhornung67** [comment]
Resolved in https://github.com/LLNL/RAJAPerf/pull/285
