### ISSUE TITLE
SYCL Kernel Implementations

### ISSUE THREAD

**Issue by homerdin** [LLNL/RAJAPerf#321]
Opening issue to track SYCL kernel implementations in the `rajaperf_sycl` branch.  Also includes support for auto work_group_size selection if `0` is given as a buildable block_size. Yes below indicates that the kernel has been implemented in a fork.  Combining the implementations into the `rajaperf_sycl` branch is in process.

| Kernel | SYCL Variant | SYCL Auto WorkGroupSize | RAJA Variant |
|---|:---:|:---:|:---:|
|Basic_DAXPY|Yes|Yes|Yes|
|Basic_DAXPY_ATOMIC|No|No|No|
|Basic_IF_QUAD|Yes|Yes|Yes|
|Basic_INDEXLIST|No|No|No|
|Basic_INDEXLIST_3LOOP|No|No|No|
|Basic_INIT3|Yes|Yes|Yes|
|Basic_INIT_VIEW1D|Yes|Yes|Yes|
|Basic_INIT_VIEW1D_OFFSET|Yes|Yes|Yes|
|Basic_MAT_MAT_SHARED|No|No|No|
|Basic_MULADDSUB|Yes|Yes|Yes|
|Basic_NESTED_INIT|Yes|Yes|Yes|
|Basic_PI_ATOMIC|No|No|No|
|Basic_PI_REDUCE|No|No|No|
|Basic_REDUCE3_INT|Yes|Yes|Yes|
|Basic_REDUCE_STRUCT|No|No|No|
|Basic_TRAP_INT|Yes|Yes|Yes|
|Lcals_DIFF_PREDICT|Yes|Yes|Yes|
|Lcals_EOS|Yes|Yes|Yes|
|Lcals_FIRST_DIFF|Yes|Yes|Yes|
|Lcals_FIRST_MIN|Yes|No|No|
|Lcals_FIRST_SUM|No|No|No|
|Lcals_GEN_LIN_RECUR|Yes|Yes|Yes|
|Lcals_HYDRO_1D|Yes|Yes|Yes|
|Lcals_HYDRO_2D|Yes|Yes|Yes|
|Lcals_INT_PREDICT|Yes|Yes|Yes|
|Lcals_PLANCKIAN|Yes|Yes|Yes|
|Lcals_TRIDIAG_ELIM|Yes|Yes|Yes|
|Polybench_2MM|Yes|Yes|Yes|
|Polybench_3MM|Yes|Yes|Yes|
|Polybench_ADI|Yes|Yes|Yes|
|Polybench_ATAX|Yes|Yes|Yes|
|Polybench_FDTD_2D|Yes|Yes|Yes|
|Polybench_FLOYD_WARSHALL|Yes|Yes|Yes|
|Polybench_GEMM|Yes|Yes|Yes|
|Polybench_GEMVER|Yes|Yes|Yes|
|Polybench_GESUMMV|Yes|Yes|Yes|
|Polybench_HEAT_3D|Yes|Yes|Yes|
|Polybench_JACOBI_1D|Yes|Yes|Yes|
|Polybench_JACOBI_2D|Yes|Yes|Yes|
|Polybench_MVT|Yes|Yes|Yes|
|Stream_ADD|Yes|Yes|Yes|
|Stream_COPY|Yes|Yes|Yes|
|Stream_DOT|No|No|No|
|Stream_MUL|Yes|Yes|Yes|
|Stream_TRIAD|Yes|Yes|Yes|
|Apps_CONVECTION3DPA|No|No|No|
|Apps_DEL_DOT_VEC_2D|Yes|Yes|Yes|
|Apps_DIFFUSION3DPA|No|No|No|
|Apps_ENERGY|Yes|Yes|Yes|
|Apps_FIR|Yes|Yes|Yes|
|Apps_HALOEXCHANGE|No|No|No|
|Apps_HALOEXCHANGE_FUSED|No|No|No|
|Apps_LTIMES|Yes|Yes|Yes|
|Apps_LTIMES_NOVIEW|Yes|Yes|Yes|
|Apps_MASS3DPA|No|No|No|
|Apps_NODAL_ACCUMULATION_3D|No|No|No|
|Apps_PRESSURE|Yes|Yes|Yes|
|Apps_VOL3D|Yes|Yes|Yes|
|Algorithm_SCAN|No|No|No|
|Algorithm_SORT|No|No|No|
|Algorithm_SORTPAIRS|No|No|No|
|Algorithm_REDUCE_SUM|No|No|No|
|Algorithm_MEMSET|No|No|No|
|Algorithm_MEMCPY|No|No|No|

**Comment by rhornung67** [comment]
Closing since this table is out-of-date and we are tracking gaps in other issues.
