### ISSUE TITLE
Checking user-supplied options correctness

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#356]
Currently, we appear are checking for user-specified option correctness for some input in `RunParams::parseCommandLineOptions()` and for other input in `Executor::setupSuite()`. 

By adding a few methods to check whether a user input string, for example, is contained in an array of strings (e.g., kernel names, variant names, etc.), we could do all correctness checking in one place. `RunParams::parseCommandLineOptions()` seems to make the most sense. Then, we could simplify logic and avoid redundancy in `Executor::setupSuite()`.

@MrBurmark what are your thoughts on this?

**Comment by MrBurmark** [comment]
That makes sense. Do we always have information like tuning names at that point?

**Comment by rhornung67** [comment]
I don't know yet. I was going to focus on simplifying the more common parsing issues issues first, like determining if specified kernels, variants, features, etc. are correct by moving that stuff out of the Executor method and putting it in methods in the RunParams class.

**Comment by rhornung67** [comment]
Reworked and merged
