### ISSUE TITLE
Question about the comparison of base and RAJA in INDEXLIST_3LOOP-Hip

### ISSUE THREAD

**Issue by chichunchen** [LLNL/RAJAPerf#367]
I'm trying to figure out why my compiler/runtime performs worse on the RAJA version than the base version for the third loop in INDEXLIST_3LOOP-Hip test (about 0.0018 for the base version and 0.0036 for the RAJA version on the third loop).

Below is the code for the third loop extracted from https://github.com/LLNL/RAJAPerf/blob/develop/src/basic/INDEXLIST_3LOOP-Hip.cpp and I found that the semantic for the base version and the RAJA version is a little different. The base version, only updates `len` at the last iteration, however, the RAJA version updates `len` at every iteration since the len in the base version is an array and the len in the RAJA version is a `ReduceSum` object and it is meant to accumulate the sum in every iteration. 

Due to the design/implementation of the test, do you expect the performance to be worse on the RAJA version? I also tried adding an overload function in ReduceSum so that the `len` can be updated at the last iteration such as the base version and it turns out the performance for the RAJA version can be much better.

Base version:
```
template < size_t block_size >
__launch_bounds__(block_size)
__global__ void indexlist_make_list(Int_ptr list,
                                    Index_type* counts,
                                    Index_type* len,
                                    Index_type iend)
{
  Index_type i = blockIdx.x * block_size + threadIdx.x;
  if (i < iend) {
    if (counts[i] != counts[i+1]) {
      list[counts[i]] = i ;
    }
    if (i == iend-1) {
      *len = counts[i+1];
    }
  }
}

// skip

      hipLaunchKernelGGL((indexlist_make_list<block_size>), grid_size, block_size, shmem, stream,
          list, counts, len, iend );
      hipErrchk( hipGetLastError() );

      hipErrchk( hipStreamSynchronize(stream) );
```

RAJA version:
```
      RAJA::forall< RAJA::hip_exec<block_size, true /*async*/> >( res,
        RAJA::RangeSegment(ibegin, iend),
        [=] __device__ (Index_type i) {
        if (counts[i] != counts[i+1]) {
          list[counts[i]] = i;
          len += 1;
        }
      });
```

**Comment by MrBurmark** [comment]
You are right, the base and RAJA cases are different semantically in the way you describe. The RAJA variant does an entire extra reduction while the base variant just looks at the result of the scan to get the final count. The implementations of these variants should be changed so they are doing the same thing.

**Comment by MrBurmark** [comment]
This will be fixed in #370.

**Comment by MrBurmark** [comment]
This should be fixed now, @chichunchen can you confirm?

**Comment by chichunchen** [comment]
Yes, I can confirm the issue has been fixed. Thanks!
