### ISSUE TITLE
Make kernel launch syntax consistent across GPU variants

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#385]
Currently, we do the following to launch GPU kernels in RAJA Perf:

- We use "triple chevron" syntax to launch CUDA base kernel variants
- We use hipLaunchKernelGGL() method to launch HIP base kernel variants
- Inside RAJA, we use cudaLaunchKernel() method to launch CUDA kernels and we use hipLaunchKernel() method to launch HIP kernels.

Should we convert all base kernel variants to use the launch kernel methods that RAJA uses internally so that we have an apples to apples comparison across all GPU variants?

Related issue: https://github.com/LLNL/RAJAPerf/issues/117

**Comment by rhornung67** [comment]
@MrBurmark @trws if you have thoughts on this issue, please add a comment.

**Comment by MrBurmark** [comment]
I think its best to switch everything to use cuda/hipLaunchKernel like we use in RAJA internally. That way its consistent.
I think the main difference between using triple chevron/GGL and cuda/hipLaunchKernel is that the triple chevron/GGL APIs make an extra copy of the arguments. The difference between triple chevron and the launchKernel APIs is that triple chevron can do template type deduction and check the argument types.
