### ISSUE TITLE
[OpenMP] use of undeclared identifier 'EDGE3D_DATA_SETUP_OMP_TARGET'

### ISSUE THREAD

**Issue by ThorBl** [LLNL/RAJAPerf#400]
I would ask you to fix the compile-time error mentioned in the title. The error is raised in EDGE3D-OMPTarget.cpp.

Thanks. :)

**Comment by rhornung67** [comment]
@ThorBl this issue is resolved in https://github.com/LLNL/RAJAPerf/pull/405
