### ISSUE TITLE
Add RAJA variants of INDEXLIST kernel

### ISSUE THREAD

**Issue by rhornung67** [LLNL/RAJAPerf#402]
There are only Base variants of this kernel. Is that intentional?

**Comment by MrBurmark** [comment]
Yes, this is meant to contrast with INDEXLIST_3LOOP. INDEXLOOP is what we used to do and had sequential dependencies and INDEXLIST_3LOOP is what we do now that we have to be able to run in parallel.

**Comment by rhornung67** [comment]
Got it. Thanks.
