### ISSUE TITLE
Running error with CUDA10.1

### ISSUE THREAD

**Issue by nanzifan** [LLNL/RAJAPerf#68]
Hi,

Does current RAJAPerf work with CUDA10.1?

I tried to run the suite with CUDA10.1, it pass all the `make test`. But when I run the suite, it gave me following error:
> Running warmup kernel variants...
> 
> Running specified kernels and variants...
> CUDAassert: an illegal memory access was encountered /home/nan1/project/RAJA_PERFSUITE/RAJAPerf/src/./common/CudaDataUtils.hpp 68
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  CUDAassert
> Aborted (core dumped)

I looked into code, the error came from the code:
```
template <typename T>
void getCudaDeviceData(T& hptr, const T dptr, int len)
{
  cudaErrchk( cudaMemcpy( hptr, dptr,
              len * sizeof(typename std::remove_pointer<T>::type),
              cudaMemcpyDeviceToHost ) );
}
```

The line 68 is `cudaMemcpyDeviceToHost`.

I tried it with CUDA9.1, it runs perfectly.

**Comment by davidbeckingsale** [comment]
What compiler flags are you using?

**Comment by nanzifan** [comment]
I adopt them from `blueos/nvcc9, gcc_7_3_1` version.

Here is the script file:
`BUILD_SUFFIX=aws_nvcc10.1_gcc7.4.0
RAJA_HOSTCONFIG=../tpl/RAJA/host-configs/aws/v100/nvcc_gcc_7_4_0.cmake

rm -rf build_${BUILD_SUFFIX} >/dev/null
mkdir build_${BUILD_SUFFIX} && cd build_${BUILD_SUFFIX}

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -C ${RAJA_HOSTCONFIG} \
  -DENABLE_OPENMP=On \
  -DENABLE_CUDA=On \
  -DENABLE_TESTS=On \
  -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.1 \
  -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.1/bin/nvcc \
  -DCUDA_ARCH=sm_70 \
  -DCMAKE_INSTALL_PREFIX=../install_${BUILD_SUFFIX} \
  "$@" \
  ..`

Here is the cmake file in RAJA/host-config.

`set(RAJA_COMPILER "RAJA_COMPILER_GNU" CACHE STRING "")

set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE PATH "")

set(CMAKE_CXX_FLAGS_RELEASE "-Ofast -finline-functions" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-Ofast -g -finline-functions" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g" CACHE STRING "")

set(HOST_OPT_FLAGS "-Xcompiler -O3 -Xcompiler -finline-functions -Xcompiler -fopenmp")

set(CMAKE_CUDA_FLAGS_RELEASE "-O3 ${HOST_OPT_FLAGS}" CACHE STRING "")set(CMAKE_CUDA_FLAGS_DEBUG "-g -G -O0" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_RELWITHDEBINFO "-g -lineinfo -O3 ${HOST_OPT_FLAGS}" CACHE STRING "")

set(RAJA_RANGE_ALIGN 4 CACHE INT "")
set(RAJA_RANGE_MIN_LENGTH 32 CACHE INT "")
set(RAJA_DATA_ALIGN 64 CACHE INT "")

set(RAJA_HOST_CONFIG_LOADED On CACHE Bool "")`

**Comment by davidbeckingsale** [comment]
Can you build with `make VERBOSE=1` and check that the same CUDA arch flag (sm_70) is passed to both the RAJA library files and the perfsuite files during compilation.

**Comment by nanzifan** [comment]
I think both of them have the CUDA arch flag. Here is two entries: one is building CUDA object in RAJA src file, the other is building in perfsuite src file.

```
[  6%] Building CUDA object tpl/RAJA/CMakeFiles/RAJA.dir/src/LockF
reeIndexSetBuilders.cpp.o
cd /home/nan1/project/RAJA_PERFSUITE/RAJAPerf/build_aws_nvcc10.1_g
cc7.4.0/tpl/RAJA && /usr/local/cuda-10.1/bin/nvcc -ccbin=/usr/bin/
g++  -I/usr/local/cuda-10.1/include -I/home/nan1/project/RAJA_PERF
SUITE/RAJAPerf/tpl/RAJA/include -I/home/nan1/project/RAJA_PERFSUIT
E/RAJAPerf/build_aws_nvcc10.1_gcc7.4.0/tpl/RAJA/include -I/home/na
n1/project/RAJA_PERFSUITE/RAJAPerf/tpl/RAJA/tpl/cub  -restrict -ar
ch sm_70 --expt-extended-lambda -O3 -Xcompiler -O3 -Xcompiler -fin
line-functions -Xcompiler -fopenmp -Xcompiler=-fPIC   -Xcompiler=-
fopenmp -std=c++11 -x cu -c /home/nan1/project/RAJA_PERFSUITE/RAJA
Perf/tpl/RAJA/src/LockFreeIndexSetBuilders.cpp -o CMakeFiles/RAJA.
dir/src/LockFreeIndexSetBuilders.cpp.o
```

```
[ 47%] Building CUDA object src/common/CMakeFiles/common.dir/RAJAPerfSuite.cpp.o
cd /home/nan1/project/RAJA_PERFSUITE/RAJAPerf/build_aws_nvcc10.1_g
cc7.4.0/src/common && /usr/local/cuda-10.1/bin/nvcc -ccbin=/usr/bi
n/g++ -DRUN_OPENMP -DRUN_RAJA_SEQ -I/home/nan1/project/RAJA_PERFSU
ITE/RAJAPerf/src/. -I/usr/local/cuda-10.1/include -I/home/nan1/pro
ject/RAJA_PERFSUITE/RAJAPerf/tpl/RAJA/include -I/home/nan1/project
/RAJA_PERFSUITE/RAJAPerf/build_aws_nvcc10.1_gcc7.4.0/tpl/RAJA/incl
ude -I/home/nan1/project/RAJA_PERFSUITE/RAJAPerf/tpl/RAJA/tpl/cub  -restrict -arch sm_70 --expt-extended-lambda -O3 -Xcompiler -O3 -Xcompiler -finline-functions -Xcompiler -fopenmp -Xcompiler=-fPIC   -Xcompiler=-fopenmp -std=c++11 -x cu -c /home/nan1/project/RAJA_PERFSUITE/RAJAPerf/src/common/RAJAPerfSuite.cpp -o CMakeFiles/common.dir/RAJAPerfSuite.cpp.o
```

**Comment by rhornung67** [comment]
@nanzifan is this still an issue for you. I've successfully built and run the latest release version of the perf suite (v0.7.0) with 3 different versions of CUDA 10.1.x.

**Comment by nanzifan** [comment]
Thanks for the noticing. It's not an issue for me any more. I'll close the issue.
