### ISSUE TITLE
CUDA build broken with GCC >= 8 for non-ppc platforms

### ISSUE THREAD

**Issue by abbotts** [LLNL/RAJAPerf#85]
Using GCC 8+ as a host compiler for the CUDA backend on x86 fails with 

```
[  0%] Building CUDA object tpl/RAJA/CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o
cd /home/users/sabbott/cuda_tests/RAJAPerf/build_v100/tpl/RAJA && /cm/shared/apps/cuda10.2/toolkit/10.2.89/bin/nvcc -ccbin=/opt/gcc/8.1.0/bin/g++  -I/cm/shared/apps/cuda10.2/toolkit/10.2.89/include -I/home/users/sabbott/cuda_tests/RAJAPerf/tpl/RAJA/include -I/home/users/sabbott/cuda_tests/RAJAPerf/build_v100/tpl/RAJA/include -I/home/users/sabbott/cuda_tests/RAJAPerf/tpl/RAJA/tpl/cub -I/home/users/sabbott/cuda_tests/RAJAPerf/tpl/RAJA/tpl/rocPRIM/rocprim/include -I/home/users/sabbott/cuda_tests/RAJAPerf/tpl/RAJA/tpl/camp/include  -Xcompiler -mno-float128 -restrict -arch sm_70 --expt-extended-lambda --expt-relaxed-constexpr -Xcudafe "--display_error_number" -O2 -Xcompiler=-fPIC   -std=c++11 -x cu -c /home/users/sabbott/cuda_tests/RAJAPerf/tpl/RAJA/src/AlignedRangeIndexSetBuilders.cpp -o CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o
g++: error: unrecognized command line option '-mno-float128'; did you mean '-mno-avx2'?
```

The issue seems to be that the RAJA submodule is new enough to include the `-mno-float128` addition but not https://github.com/LLNL/RAJA/commit/b559f0a28f32134d2b3e15a275899f1df10aafa8 to make it only restrict to PPC platforms, where `-m[no-]float127` is a valid option. To continue testing I cherry-picked that change forward, which worked sans an out-of-bound read in one test for which I'll open a new issue. I haven't tried moving the submodule forward, so I can't say how that will work.

**Comment by abbotts** [comment]
This no longer reproduces. Probably fixed by a RAJA update years ago.

**Comment by rhornung67** [comment]
Thanks @abbotts for closing the issue.
