### ISSUE TITLE
Kernel max time calc

### ISSUE THREAD

**Issue by markendr** [LLNL/RAJAPerf#87]
Hi,

I may be missing something but it looks like the max_time calc in KernelBase.cpp has a typo. Should max_time update be taking max() of max_time and new exec_time as shown in the following patch?

```
--- a/src/common/KernelBase.cpp
+++ b/src/common/KernelBase.cpp
@@ -76,7 +76,7 @@

   RAJA::Timer::ElapsedType exec_time = timer.elapsed();
   min_time[running_variant] = std::min(min_time[running_variant], exec_time);
-  max_time[running_variant] = std::max(min_time[running_variant], exec_time);
+  max_time[running_variant] = std::max(max_time[running_variant], exec_time);
   tot_time[running_variant] += exec_time;
 }
```

**Comment by rhornung67** [comment]
@markendr Good catch! A new release of the Perf Suite will be available within a day or two and will include a fix to the issue you pointed out.  Thank you.
